version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: healthcare-postgres

    restart: always

    environment:
      POSTGRES_DB: healthcare_db
      POSTGRES_USER: healthcare_admin
      POSTGRES_PASSWORD: healthcare123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: